%% routing cell 2074 to the smaller souble cell 2075 
T74 = load('Y:\Whiskernas\Data\Trial_Contacts_For_Curation\S1ForJon2\TArrays\trial_array_2074.mat')%bigger array 
T75 = load('Y:\Whiskernas\Data\Trial_Contacts_For_Curation\S1ForJon2\TArrays\trial_array_2075.mat')%smaller array 

[~, ~, keepThese] = intersect(T75.T.trialNums, T74.T.trialNums);

load('Y:\Whiskernas\Data\Trial_Contacts_For_Curation\S1ForJon2\FINISHED_CONTACTS\ConTA_2074.mat')
contacts = contacts(keepThese)


load('Y:\Whiskernas\Data\Trial_Contacts_For_Curation\S1ForJon2\AutoGeneratedContacts\ConTA_2075.mat', 'params')%for params


saveName = [  'ConTA_' T75.T.projectDetails.cellNumberForProject '.mat' ]
                    save(saveName, 'contacts', 'params');
%% both work 

%% routing cell 2074 to the smaller souble cell 2075 
T74 = load('Y:\Whiskernas\Data\Trial_Contacts_For_Curation\S1ForJon2\TArrays\trial_array_2074.mat')%bigger array 
T75 = load('Y:\Whiskernas\Data\Trial_Contacts_For_Curation\S1ForJon2\TArrays\trial_array_2075.mat')%smaller array 

[~, ~, keepThese] = intersect(T75.T.trialNums, T74.T.trialNums);

load('Y:\Whiskernas\Data\Trial_Contacts_For_Curation\S1ForJon2\FINISHED_CONTACTS\ConTA_2074.mat')
contacts2 = contacts(keepThese);
params2 = params;
params2.trialList  = params2.trialList( keepThese);
params2.trialNums  = params2.trialNums( keepThese);

% load('Y:\Whiskernas\Data\Trial_Contacts_For_Curation\S1ForJon2\AutoGeneratedContacts\ConTA_2075.mat')%for params

contacts = contacts2 ;
params = params2;
saveName = [  'ConTA_' T75.T.projectDetails.cellNumberForProject '.mat' ]
                    save(saveName, 'contacts', 'params');